# Enforce Node and pnpm versions specified in `engines` field of `package.json`
engineStrict: true

# Use whichever pnpm version is available in the environment
managePackageManagerVersions: false

# Manage peer dependencies explicitly and predictibly
strictPeerDependencies: true

# Fail install if any dependency has unreviewed build scripts
strictDepBuilds: true
onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'

# Don't install dependency versions that are less than a day old
minimumReleaseAge: 1440

# Save exact dependency versions in `package.json`
savePrefix: ''
